Enchere/Enchere/Models/Objet.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace Enchere.Models
{
    public class Objet
    {
        public int Id { get; set; }
        //[Required]
        [Display(Name = "Nom")]
        public string objetNom { get; set; }

        [Display(Name = "Déscription")]
        [AllowHtml]
        public string objetDescription { get; set; }
        [Display(Name = "Prix")]
        public double objetPrixDepart { get; set; }

        [Display(Name = "Date inscription")]
        public DateTime objetDateInsc { get; set; }     

                
        [Display(Name = "Durée Vente")]
        public int objetDureeVente { get; set; }

        private ApplicationDbContext db = new ApplicationDbContext();

        //Status de l'objet programmé coté serveur.  La codification actuelle c'est: "Vendu","Expire" et "En Vente". Peut-etre qu'il faudrait penser à une enumeration à la place.
        [Display(Name = "Statut")]
        public enumStatutObjet Statut{ get {
                DateTime dateLimite = this.objetDateInsc.AddDays(this.objetDureeVente);
                if (DateTime.Now >= dateLimite) {                    
                    if (db.Encherees.Where(a => a.ObjetId == Id).Any()) return enumStatutObjet.VD;
                    return enumStatutObjet.EX;
                }
                return enumStatutObjet.EV;
            }}

        [Display(Name = "image")]
        public string objetImage { get; set; }

        [Display(Name = "Catégorie")]
        public int categoryId { get; set; }

        public string UserId { get; set; }

        public virtual Categorie Category { get; set; }
        public virtual ApplicationUser  User { get; set; }

        [NotMapped]
        public bool notifie=false;

    }
    
}

Enchere/Enchere/Models/ObjetViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Enchere.Models
{
    public class ObjetViewModel
    {
        public string ObjetNom { get; set; }
        public Objet monObjet { get; set; }
        public IEnumerable<Encheree> Items{ get; set; }
    }
}

Enchere/Enchere/Models/ObjetsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Enchere.Models
{
    public class ObjetsViewModel
    {
        public IList<Categorie> Categorie { get; set; }
        public IList<Encheree> Enchere { get; set; }
    }
}

Enchere/Enchere/Controllers/ObjetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Enchere.Models;
using WebApplication1.Models;
using System.IO;
using Microsoft.AspNet.Identity;
using MoreLinq;
using System.Net.Mail;

namespace Enchere.Controllers
{
    [Authorize]
    //[Authorize(Roles = "Admin")]
    public class ObjetsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Objets
        public ActionResult Index()
        {
            var objets = db.Objets.Include(o => o.Category);
            return View(objets.ToList());
        }

        // GET: Objets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Objet objet = db.Objets.Find(id);
            if (objet == null)
            {
                return HttpNotFound();
            }
            return View(objet);
        }

        // GET: Objets/Create
        public ActionResult Create()
        {
            ViewBag.categoryId = new SelectList(db.Categories, "Id", "CategoryName");
            return View();
        }

        // POST: Objets/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Objet objet, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {

                string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                upload.SaveAs(path);
                objet.objetImage = upload.FileName;
                objet.UserId = User.Identity.GetUserId();
                objet.objetDateInsc = DateTime.Now;
                db.Objets.Add(objet);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.categoryId = new SelectList(db.Categories, "Id", "CategoryName", objet.categoryId);
            return View(objet);
        }

        // GET: Objets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Objet objet = db.Objets.Find(id);
            if (objet == null)
            {
                return HttpNotFound();
            }
            ViewBag.categoryId = new SelectList(db.Categories, "Id", "CategoryName", objet.categoryId);
            return View(objet);
        }

        // POST: Objets/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Objet objet, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                string oldPath = Path.Combine(Server.MapPath("~/Uploads"), objet.objetImage);


                if (upload != null)
                {
                    System.IO.File.Delete(oldPath);
                    string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                    upload.SaveAs(path);
                    objet.objetImage = upload.FileName;

                }


                db.Entry(objet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.categoryId = new SelectList(db.Categories, "Id", "CategoryName", objet.categoryId);
            return View(objet);
        }

        // GET: Objets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Objet objet = db.Objets.Find(id);
            if (objet == null)
            {
                return HttpNotFound();
            }
            return View(objet);
        }

        // POST: Objets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Objet objet = db.Objets.Find(id);
            db.Objets.Remove(objet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



        [Authorize]
        // Rapport #2 
        //Liste des objets vendus par un membre incluant l’information sur le prix
        //de départ et le prix final.       

        //[Authorize(Roles = "Vendeur,Admin")]
        public ActionResult GetListeObjetVenduWithPrix()
        {
            var groupe = (from fuss in db.Objets
                          join ench in db.Encherees
                          on fuss.Id equals ench.ObjetId
                          select new { fuss, ench });

            var liste = from o in groupe
                        group o by new { o.fuss.User.UserName, o.fuss.Id }

                          into gr
                        select new RaportObjetVenduPrixModel
                        {
                            MembreVendeur = gr.FirstOrDefault().fuss.User.UserName,
                            ObjetName = gr.Select(a => a.fuss.objetNom).FirstOrDefault(),
                            ObjetCategorie = gr.Select(a => a.fuss.Category.CategoryName).FirstOrDefault(),
                            PrixInitial = gr.Select(a => a.fuss.objetPrixDepart).FirstOrDefault(),
                            PrixFinal = gr.Select(a => a.ench.niveauMax).Max()

                        };
            return View(liste.ToList());
        }

        //objets vendu par chaque membre
        [Authorize]
        public ActionResult GetObjetmise()
        {
            var UserId = User.Identity.GetUserId();

            var objets = db.Objets.Where(a => a.UserId == UserId);
            return View(objets.ToList());
        }



        //objets vendu par chaque membre et vendu
        [Authorize]
        public ActionResult GetObjetmiseVendu()
        {
            var UserId = User.Identity.GetUserId();

            var objets = db.Objets.Where(a => a.UserId == UserId);
            return View(objets.ToList());
        }

        //objets vendu par chaque membre
        [Authorize]
        public ActionResult GetObjetAchte()
        {                    
                      
                var UserId = User.Identity.GetUserId();
             

                if (db.Encherees.Where(a => a.UserId == UserId).Any())
                {
                    var objets = db.Encherees.GroupBy(l => l.ObjetId).
                        Select(g => g.OrderByDescending(c => c.UserId).FirstOrDefault()).
                        Where(u => u.UserId == UserId);
                
                    return View(objets.ToList());
                    //var objets = db.Encherees.Where(a => a.UserId == UserId);
                    //return View(objets.DistinctBy(a => a.ObjetId).ToList());
                }
                else
                {
                    List<Encheree> list = new List<Encheree>();                   
                    return View(list);

                }
            
                       
                       
        }

  // GET: Evaluations/Create
        public ActionResult CreateEval(int objetId)
        {
             Session["ObjetId"]= objetId;
            var ObjetId = (int)Session["ObjetId"];

            var obj = db.Objets.Where(a => a.Id == objetId).Single();
            ViewBag.Vendeur = obj.User.UserName;

            ViewBag.Name = User.Identity.Name;
            //ViewBag.UserId = new SelectList(db.Users, "Id", "Civilite");
            return View(); 

        }



        // POST: Evaluations/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateEval([Bind(Include = "Id,DateEvaluation,Cote,Commentaire,Vendeur,UserId")] Evaluation evaluation)
        {
            if (ModelState.IsValid)
            {
                evaluation.UserId = User.Identity.GetUserId();
                evaluation.DateEvaluation = DateTime.Now;

                var ObjetId = (int)Session["ObjetId"];

                var obj = db.Objets.Where(a => a.Id == ObjetId).Single();
                evaluation.Vendeur = obj.User.UserName;

                //check sum cote
                double total = 0;

                //On regarde si il y a une evaluation existante pour l'utilisateur donné
                if (db.Evaluations.Where(a => a.Vendeur == obj.User.UserName).Any())
                {
                    total = (from eval in db.Evaluations

                             where eval.Vendeur == obj.User.UserName
                             select eval.Cote).Sum();

                }

                evaluation.TotalCote = total + evaluation.Cote;

                //send notification


                ViewBag.total = evaluation.TotalCote;
                db.Evaluations.Add(evaluation);
                db.SaveChanges();
                if (evaluation.TotalCote <= -6)
                {
                    envoiMail(obj.User);
                }
                if (evaluation.TotalCote <= -9)
                {

Enchere/Enchere/Views/Objets/Create.cshtml
@model Enchere.Models.Objet

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Créer votre objet</h2>
<script src="~/Scripts/ckeditor/ckeditor.js"></script>

@using (Html.BeginForm("Create", "Objets", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">

        <div class="alert alert-danger" id="error-div" style="display:none;">
            <span id="view-err">


            </span>
        </div>
    </div>
    <div class="form-horizontal">

        <h4>Objet</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.objetNom, htmlAttributes: new { @class = "control-label col-md-2" })

            <div class="col-md-10">
                @Html.EditorFor(model => model.objetNom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.objetNom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.objetDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.objetDescription, new { htmlAttributes = new { @class = "form-control", @id = "objetDescription" } })
                @Html.ValidationMessageFor(model => model.objetDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.objetPrixDepart, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.objetPrixDepart, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.objetPrixDepart, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.objetDateInsc, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.objetDateInsc, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.objetDateInsc, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.objetDureeVente, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.objetDureeVente, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.objetDureeVente, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.objetDateAchat, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.objetDateAchat, new { htmlAttributes = new { @class = "form-control datepicker", @id = "datePicker" } })
                    @Html.ValidationMessageFor(model => model.objetDateAchat, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.objetImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="upload" id="myImage" />
                @Html.ValidationMessageFor(model => model.objetImage, "", new { @class = "text-danger" })
            </div>
        </div>
            @*********************************************
                DropArear debut
            **********************************************@
        <div class="form-group">
            <label class="control-label col-md-2">Glisser les fichiers</label>
            @*@Html.LabelFor(model => model.objetImage, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10" id="dropArea">
                Drop your files here
            </div>

        </div>
        <div class="form-group">
            <label class="control-label col-md-2"> Fichiers téléchargés </label>
            <div class="col-md-10">
                <ul class="list-group" id="uploadList"></ul>
            </div>
        </div>

            @*********************************************
                DropArear  fin
            **********************************************@

        <div class="form-group">
           <label class="control-label col-md-2" > Nom de la catégorie</label>
            @* @Html.LabelFor(model => model.categoryId, "categoryId", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.DropDownList("categoryId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.categoryId, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
                <label class="col-xs-3 control-label">Date</label>
                <div class="col-xs-5 date">
                    <div class="input-group input-append date" id="datePicker">
                        <input type="text" class="form-control" name="date" />
                        <span class="input-group-addon add-on"><span class="glyphicon glyphicon-calendar"></span></span>
                    </div>
                </div>
            </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" id="Create" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la liste", "Index")
</div>

<style>
    #dropArea {
        background: #b5b5b5;
        border: black dashed 1px;
        height: 250px;
        text-align: center;
        color: #fff;
        padding-top: 12px;
    }

    .active-drop {
        background: #77bafa !important;
        border: solid 2px blue !important;
        opacity: .5;
        color: black !important;
    }
</style>

<script>
    CKEDITOR.replace("objetDescription")



</script>

@*Ajout validation creation image*@

@section scripts
    {
    <script src="~/Scripts/jquery.filedrop.js"></script>

    <script>


        $(function () {
            $('#datePicker')
                .datepicker({
                    format: 'yyyy/mm/dd'
                })
                .on('changeDate', function (e) {
                    // Revalidate the date field
                    $('#eventForm').formValidation('revalidateField', 'date');
                });
            //$('.datepicker').datepicker(); //Initialise any date pickers

            $("#Create").click(function () {

                //verifie si input empty
                /*if ($("#myImage").val() == "") {

                    $("#error-div").fadeIn();
                    $("#view-err").append("veuillez charger l'image de l'objet");
                    return false;
                }*/

                if ($("#myImage").val() != "") {
                    //verifie si extension is valid
                    var filename = document.getElementById("myImage").value;
                    var extensionImg = filename.substr(filename.lastIndexOf('.') + 1);
                    var validExtension = ['jpg', 'png', 'gif', 'bmp'];
                    if ($.inArray(extensionImg, validExtension) == -1) {

                        $("#error-div").fadeIn();
                        $("#view-err").append("format incorrecte");
                        return false;

                    }
                    //verifie si size valid 2m

                    var myfilesize = document.getElementById("myImage").files[0].size / 1024 / 1024;
                    if (myfilesize > 2) {

                        $("#error-div").fadeIn();
                        $("#view-err").append("size sup a 2m ");
                        return false;
                    }
                }
            });

            //drag and drop files Début

            $('#dropArea').filedrop({
                url: '@Url.Action("UploadFiles")',
                allowedfiletypes: ['image/jpeg', 'image/png', 'image/gif'],
                allowedfileextensions: ['.jpg', '.jpeg', '.png', '.gif'],
                paramname: 'files',
                maxfiles: 5,
                maxfilesize: 5, // in MB
                dragOver: function () {
                    $('#dropArea').addClass('active-drop');
                },
                dragLeave: function () {
                    $('#dropArea').removeClass('active-drop');
                },
                drop: function () {
                    $('#dropArea').removeClass('active-drop');
                },
                afterAll: function (e) {
                    $('#dropArea').html('file(s) uploaded successfully');
                },
                uploadFinished: function (i, file, response, time) {
                    $('#uploadList').append('<li class="list-group-item">' + file.name + '</li>')
                }
            })
            //drag and drop files fin
        });

    </script>


}

Enchere/Enchere/Views/Objets/CreateEval.cshtml
@model Enchere.Models.Evaluation

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Evaluation vendeur</h2>
<script src="~/Scripts/ckeditor/ckeditor.js"></script>

@using (Html.BeginForm("CreateEval", "Objets", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Evaluation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Vendeur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="glyphicon glyphicon-user img-size"></span>
                @Html.LabelFor(model => model.Vendeur, (string)ViewBag.Vendeur, new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.Vendeur, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Cote, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Cote, new SelectList(new[]{"Evaluez-moi","-3","-2","-1", "+1", "+2", "+3" }))
                @*@Html.EditorFor(model => model.Cote, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Cote, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Commentaire, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Commentaire, new { htmlAttributes = new { @class = "form-control", @id = "Commentaire" } })
                @Html.ValidationMessageFor(model => model.Commentaire, "", new { @class = "text-danger" })
            </div>
        </div>





        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="évaluer" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>
    CKEDITOR.replace("Commentaire")



</script>

Enchere/Enchere/Views/Objets/CreateEvalAchteur.cshtml
@model Enchere.Models.Evaluation

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Evaluation Achteur</h2>
<script src="~/Scripts/ckeditor/ckeditor.js"></script>

@using (Html.BeginForm("CreateEvalAchteur", "Objets", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Evaluation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span class="glyphicon glyphicon-user img-size"></span>
                @Html.LabelFor(model => model.UserId, (string)ViewBag.Acheteur, new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Cote, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Cote, new SelectList(new[] { "Evaluez-moi", "-3", "-2", "-1", "+1", "+2", "+3" }))
                @*@Html.EditorFor(model => model.Cote, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Cote, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Commentaire, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Commentaire, new { htmlAttributes = new { @class = "form-control", @id = "Commentaire" } })
                @Html.ValidationMessageFor(model => model.Commentaire, "", new { @class = "text-danger" })
            </div>
        </div>





        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="évaluer" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>
    CKEDITOR.replace("Commentaire")



</script>

Enchere/Enchere/Views/Objets/Delete.cshtml
@model Enchere.Models.Objet

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Objet</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.objetNom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.objetNom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.objetDescription)
        </dt>

        <dd>
            @Html.Raw(HttpUtility.HtmlDecode(Html.DisplayFor(model => model.objetDescription).ToString()))
            @*@Html.DisplayFor(model => model.objetDescription)*@
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.objetPrixDepart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.objetPrixDepart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.objetDateInsc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.objetDateInsc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.objetDureeVente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.objetDureeVente)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.objetDateAchat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.objetDateAchat)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.objetImage)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model => model.objetImage)" class="thumbnail" style="width:48px;height:48px;" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Enchere/Enchere/Views/Objets/Details.cshtml
@model Enchere.Models.Objet

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Objet</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.objetNom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.objetNom)
        </dd>

        <dt>        
            @Html.DisplayNameFor(model => model.objetDescription)
        </dt>

        <dd>
            @Html.Raw(HttpUtility.HtmlDecode(Html.DisplayFor(model => model.objetDescription).ToString()))
           
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.objetPrixDepart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.objetPrixDepart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.objetDateInsc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.objetDateInsc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.objetDureeVente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.objetDureeVente) 
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.objetDateAchat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.objetDateAchat)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.objetImage)
        </dt>

        <dd>
            <img src="~/Uploads/@Html.DisplayFor(model => model.objetImage)" class="thumbnail" style="width:48px;height:48px;"/>
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>