Enchere/Enchere/Controllers/EnchereesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Enchere.Models;
using WebApplication1.Models;
using Microsoft.AspNet.Identity;
using MoreLinq;

namespace Enchere.Migrations
{
    public class EnchereesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private Encheree newOffre;
        // GET: Encherees
        public ActionResult Index()
        {
            var encherees = db.Encherees.Include(e => e.objet).Include(e => e.user);
            return View(encherees.ToList());
        }

        // GET: Encherees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Encheree encheree = db.Encherees.Find(id);
            if (encheree == null)
            {
                return HttpNotFound();
            }
            return View(encheree);
        }

        [Authorize]
        public ActionResult Appliquer()
        {            
            return View();
        }

        [HttpPost]
        public ActionResult Appliquer(Enchere.Models.Encheree offreEnchere)
        {
            var UserId = User.Identity.GetUserId();
            var ObjetId = (int)Session["ObjetId"];
            Objet objet = (Objet)db.Objets.Where(a => a.Id == ObjetId).First();

            string message = "";
            double niveauActuel = 0;
            bool bonPrixDepart = false;

            Encheree derniereOffre = offreEnchere;
            DateTime dateLimite = objet.objetDateInsc.AddDays(objet.objetDureeVente);

            //est-ce qu'il y a deja une offre placé?
            if (db.Encherees.Where(a => a.ObjetId == ObjetId).Any())
            {
                niveauActuel = db.Encherees.Where(a => a.ObjetId == ObjetId).ToList().Max(m => m.enchereNiveau);
                derniereOffre = db.Encherees.Where(a => a.ObjetId == ObjetId).ToList().MaxBy(m => m.enchereNiveau);
                bonPrixDepart = true;
            }
            //est-ce que la premiere offre est acceptable
            else
            {
                if (offreEnchere.enchereNiveau > objet.objetPrixDepart)
                {
                    bonPrixDepart = true;                    
                }                
            }   

            if (offreEnchere.enchereNiveau > niveauActuel && bonPrixDepart &&
                UserId != derniereOffre.UserId && dateLimite > DateTime.Now && objet.UserId != UserId)
            {
                var offre = checkEnchere(offreEnchere, niveauActuel, bonPrixDepart);
                offre.UserId = UserId;
                offre.ObjetId = ObjetId;
                offre.Message = offreEnchere.Message;
                offre.enchereNiveau = offreEnchere.enchereNiveau;
                offre.enchereDate = DateTime.Now;
                offre.niveauMax = offreEnchere.niveauMax;


                db.Encherees.Add(offre);
                message = "Bravo! Vous venez de surrenchérir!!";
                db.SaveChanges();

                if (newOffre != null)
                {
                    newOffre.ObjetId = ObjetId;
                    newOffre.enchereDate = DateTime.Now;
                    newOffre.Message = "Surrencherissement automatique";

                    db.Encherees.Add(newOffre);
                    message = "Bien Esseyé sauf qu'il va falloir surrenchérir pour gagner!!";
                }
                db.SaveChanges();

                TempData["Result"] = message;

                return RedirectToAction("Index");

            }
            else
            {
                if(derniereOffre.UserId == UserId)
                {
                    message = "Vous ne devez pas encherir.Vous détenez déjà l'enchere avec une offre de :"+ niveauActuel +"$.";
                }
                else if (dateLimite < DateTime.Now)
                {
                    message = "Erreur!! L'enchere est Expiré depuis " + dateLimite + ".";
                }
                else if (!bonPrixDepart)
                {
                    message = "L'offre que vous venez de faire est inférieure ou égale au prix initial qui est de " + objet.objetPrixDepart + "$";
                }
                else if (objet.UserId == UserId)
                {
                    message = "Vous ne pouvez pas faire une offre sur un objet que vous vendez";
                }                
                else
                {
                    message = "Le montant que vous proposé est inférieur ou égal au niveau actuel qui est de " + niveauActuel + " $.";
                }
                ViewBag.Result = message;
                return View();
            }


        }


        private Encheree checkEnchere(Encheree offreActuelle, double niveauActuel, bool premiereOffre)
        {
            var ObjetId = (int)Session["ObjetId"];
            Objet objet = (Objet)db.Objets.Where(a => a.Id == ObjetId).First();

            newOffre = null;

            //est-ce qu'il y a déjà une o frre placée?
            if (db.Encherees.Where(a => a.ObjetId == ObjetId).Any())
            {
                var offreMax = db.Encherees.Where(a => a.ObjetId == ObjetId).ToList().MaxBy(m => m.niveauMax);

                if (offreActuelle.enchereNiveau >= offreMax.niveauMax)
                {
                    offreActuelle.niveauMax = offreActuelle.enchereNiveau;

                    if(offreActuelle.enchereNiveau != offreMax.niveauMax)
                    {
                    offreActuelle.enchereNiveau = offreMax.niveauMax + 1;
                    }

                    //notifier User ici par email
                    var idUser = offreMax.UserId;
                    
                    /*string subject = " Enchère dépassée";

                        string body = "votre enchère à été dépassée ";

                        Controllers.AccountController.EnvoiMessage(item.User.Email, body, subject);
                     */
                    return offreActuelle;
                }
                else
                {
                    //Des tests doivent encore etre faits
                    offreActuelle.niveauMax = offreMax.niveauMax;

                    newOffre = new Encheree();
                    newOffre.niveauMax = offreMax.niveauMax;
                    newOffre.enchereNiveau = offreActuelle.enchereNiveau + 1;
                    newOffre.UserId = offreMax.UserId;

                    return offreActuelle;
                }
            }
            else
            {
                offreActuelle.niveauMax = offreActuelle.enchereNiveau;
               
                if(offreActuelle.enchereNiveau - objet.objetPrixDepart > 1)
                {
                    offreActuelle.enchereNiveau = objet.objetPrixDepart + 1;
                }
                return offreActuelle;
            }           

        }

        // GET: Encherees/Create
        public ActionResult Create()
        {
            ViewBag.ObjetId = new SelectList(db.Objets, "Id", "objetNom");
            ViewBag.UserId = new SelectList(db.Users, "Id", "Civilite");
            return View();
        }

        // POST: Encherees/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,enchereNiveau,Message,niveauMax,enchereDate,ObjetId,UserId")] Encheree encheree)
        {
            if (ModelState.IsValid)
            {
                db.Encherees.Add(encheree);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ObjetId = new SelectList(db.Objets, "Id", "objetNom", encheree.ObjetId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Civilite", encheree.UserId);
            return View(encheree);
        }

        // GET: Encherees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Encheree encheree = db.Encherees.Find(id);
            if (encheree == null)
            {
                return HttpNotFound();
            }
            ViewBag.ObjetId = new SelectList(db.Objets, "Id", "objetNom", encheree.ObjetId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Civilite", encheree.UserId);
            return View(encheree);
        }

        // POST: Encherees/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,enchereNiveau,Message,niveauMax,enchereDate,ObjetId,UserId")] Encheree encheree)
        {
            if (ModelState.IsValid)
            {
                db.Entry(encheree).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ObjetId = new SelectList(db.Objets, "Id", "objetNom", encheree.ObjetId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Civilite", encheree.UserId);
            return View(encheree);
        }

        // GET: Encherees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Encheree encheree = db.Encherees.Find(id);
            if (encheree == null)
            {

Enchere/Enchere/Views/Home/About.cshtml
@{
    ViewBag.Title = "A propos";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<div class="container-fluid">
   



    <p style="margin-left:120px">&nbsp;</p>

    <p style="margin-left:40px"><span style="font-size:20px"><strong>Identification du propri&eacute;taire du site</strong></span></p>

    <p style="margin-left:40px">
        Le site <strong>www.Munarela-Enchéres.ca</strong> appartient et est g&eacute;r&eacute; par la soci&eacute;t&eacute;<strong> MUNARELAsprl </strong>dont le si&egrave;ge social est situé au Canada<br />
        <br />
        Num&eacute;ro TVA&nbsp;: TVA BE0859.695.954
    </p>

    <p style="margin-left:40px"><strong><span style="font-size:20px">Contact</span></strong></p>

    <p style="margin-left:40px">E-mail :<span style="color:#FF0000"> </span><a href="http://localhost:15640/Home/Contact"><span style="color:#FF0000">munarela2@gmail.com</span></a></p>

    <p style="margin-left:40px">Support technique : <a href="http://localhost:15640/Home/Contact"><span style="color:#FF0000">munarela2@gmail.com</span></a></p>

    <p style="margin-left:40px"><span style="font-size:20px"><strong>R&eacute;alisation et h&eacute;bergement du site</strong></span></p>

    <p style="margin-left:40px">
        Le site a &eacute;t&eacute; r&eacute;alis&eacute; par la soci&eacute;t&eacute; GénieWeb.com, resp. 2030 Pie IX Canada<br />
        Site programm&eacute; en C# ASP.NET .
    </p>

    <p style="margin-left:40px"><strong><span style="font-size:20px">Droits d&rsquo;auteur</span></strong></p>

    <p style="margin-left:40px">Le site internet, sa structure g&eacute;n&eacute;rale, les textes, les illustrations,&hellip; et tout autre &eacute;l&eacute;ment composant le site sont la propri&eacute;t&eacute; de la soci&eacute;t&eacute; <strong>MUNARELAsprl </strong>pour . Toute copie, adaptation, traduction de tout ou d&rsquo;une partie de ce site est strictement interdite sans l&rsquo;autorisation pr&eacute;alable et par &eacute;crit de la soci&eacute;t&eacute; <strong>MUNARELAsprl</strong>.</p>

    <p style="margin-left:40px"><span style="font-size:20px"><strong>Marques</strong></span></p>

    <p style="margin-left:40px">La d&eacute;nomination<strong> Munarela-Enchéres</strong> et le logo <strong>Munarela-Enchéres</strong> sont des marques d&eacute;pos&eacute;es appartenant &agrave; <strong>MUNARELAsprl</strong> et prot&eacute;g&eacute;es &agrave; ce titre par le droit de la propri&eacute;t&eacute; intellectuelle.</p>

    <p style="margin-left:40px"><span style="font-size:20px"><strong>Respect de la vie priv&eacute;e</strong></span></p>

    <p style="margin-left:40px">
        L&rsquo;utilisateur peut consulter librement le site sans devoir fournir ses donn&eacute;es personnelles. Les informations collect&eacute;es par <strong>MUNARELAsprl</strong> notamment via l&rsquo;E-mail de contact, le formulaire de candidature ou le formulaire d&rsquo;inscription, sont trait&eacute;es avec la plus grande confidentialit&eacute; et sont r&eacute;serv&eacute;es &agrave; l&#39;usage exclusif de <strong>MUNARELAsprl</strong>. L&#39;utisateur est libre de demander la rectification de ses donn&eacute;es ou la suppression de celles-ci par courrier postal.<br />
        &nbsp;
    </p>

    <p style="margin-left:40px"><span style="font-size:20px"><strong>R&egrave;gles g&eacute;n&eacute;rales pour les ench&egrave;res du site Munarela-Enchéres.be</strong></span></p>

    <p style="margin-left:40px">Seules les conditions de ce site sont acceptables et pratiquables. Munarela-Enchéres et GénieWeb.com sont les seuls pouvant d&eacute;sactiver un compte ne respectant pas les r&egrave;gles et conditions g&eacute;n&eacute;rales.</p>

    <p style="margin-left:40px">&nbsp;</p>
    </div>

Enchere/Enchere/Views/Home/Contact.cshtml
@model Enchere.Models.ContactModel
@using CaptchaMvc.HtmlHelpers

@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Contact</h2>
<script src="~/Scripts/ckeditor/ckeditor.js"></script>

@using (Html.BeginForm("Contact", "Home", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <div class="form-horizontal">
        <h4>Nous contacter</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control", required="required" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" , required = "required" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Message, new { htmlAttributes = new { @class = "form-control", @id = "Message", required = "required" } })
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
                <br />
                @Html.Captcha(4)
                @*@Html.MathCaptcha()*@
                <p style="color:red">  @ViewBag.ErrMessage </p>
           

            </div>
        </div>    
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Envoyer" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List ", "Index")
</div>


    <script>
        CKEDITOR.replace("Message");



    </script>

Enchere/Enchere/Views/Home/Delete.cshtml
@model Enchere.Models.Encheree

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Encheree</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.objet.objetNom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.objet.objetNom)
        </dd>

        
          <dt>
            @Html.DisplayNameFor(model => model.enchereNiveau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.enchereNiveau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.enchereDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.enchereDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Enchere/Enchere/Views/Home/DetailEnchere.cshtml
@model Enchere.Models.Encheree

@{
    ViewBag.Title = "DetailEnchere";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>DetailEnchere</h2>

<div>
    <h4>Encheree</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.objet.objetNom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.objet.objetNom)
        </dd>

         <dt>
            @Html.DisplayNameFor(model => model.enchereNiveau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.enchereNiveau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.enchereDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.enchereDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Enchere/Enchere/Views/Home/Details.cshtml
@model Enchere.Models.ObjetViewModel
@using Enchere.Models

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>@Html.DisplayFor(model => model.monObjet.objetNom)</h2>
<div class="container">
    <div class="container col-md-3 img-thumbnail" style="width:50% ; float:left">
        <div class="dl-horizontal ">
            @*<h4 class="dl-horizontal">@Html.DisplayFor(model => model.monObjet.Category.CategoryName)</h4>*@
            <p class="demo notranslate" id="CountDown"> </p>
                <dl>
                    @*<dt>
                            @Html.DisplayNameFor(model => model.monObjet.objetImage)
                        </dt>*@
                    <dd>
                        <img src="~/Uploads/@Html.DisplayFor(model => model.monObjet.objetImage)" style="width:50%;height:50%;" />
                    </dd>
                    <dt>
                        @*@Html.DisplayNameFor(model => model.monObjet.Category.CategoryName)*@
                        Catégorie
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.monObjet.Category.CategoryName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.monObjet.objetNom)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.monObjet.objetNom)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.monObjet.objetDescription)
                    </dt>

                    <dd>
                        @Html.Raw(HttpUtility.HtmlDecode(Html.DisplayFor(model => model.monObjet.objetDescription).ToString()))
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.monObjet.objetPrixDepart) Initial
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.monObjet.objetPrixDepart) $
                    </dd>

                    <dt>
                        @*@Html.DisplayNameFor(model => model.monObjet.objetDateInsc)*@
                        Date dépôt
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.monObjet.objetDateInsc)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.monObjet.objetDureeVente)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.monObjet.objetDureeVente) jours
                    </dd>

                    @*<dt>
                            @Html.DisplayNameFor(model => model.monObjet.objetDateAchat)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.monObjet.objetDateAchat)
                        </dd>*@



                </dl>
        </div>
        <p>
            @if (Model.monObjet.Statut == Enchere.Models.enumStatutObjet.EV)
            {
                @Html.ActionLink("Enchérir", "Appliquer", "Encherees", new { id = Model.monObjet.Id }, new { @class = "btn btn-primary" })
            }

            | @Html.ActionLink("Retour à la liste", "Index", new { @class = "btn btn-default" })
        </p>
    </div>
    <div class="container" style="width:50%; float:right">
        <h4>Historique Enchères</h4>
        <div class="table-responsive">
            <table id="userstable" class="table" style="width:100%">
                <thead>
                    <tr>
                        <th>Montant</th>
                        <th>Date</th>
                        <th>Enchireur</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Items)
                    {
                        <tr>
                            <td>

                                @Html.DisplayFor(modelItem => item.enchereNiveau) $
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.enchereDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.user.UserName)
                            </td>
                            @*@Html.DisplayFor(modelItem => item.user.UserName)
                            <br />*@
                        </tr>
                    }
                </tbody>
            </table>
            </div>
        </div>
    </div>
<script>
    // Update the count down every 1 second
    var x = setInterval(function () {

        // Set the date we're counting down to
        var countDownDate = new Date("@Model.monObjet.objetDateInsc.AddDays(Model.monObjet.objetDureeVente).ToString("MM dd yyyy HH:MM:ss")").getTime();

        // Get todays date and time
        var now = new Date().getTime();

        // Find the distance between now an the count down date
        var distance = countDownDate - now;

        // Time calculations for days, hours, minutes and seconds
        var days = Math.floor(distance / (1000 * 60 * 60 * 24));
        var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
        var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
        var seconds = Math.floor((distance % (1000 * 60)) / 1000);

        // Display the result in the element with id="demo"
        document.getElementById("CountDown").innerHTML = days + "J " + hours + "h "
                + minutes + "m " + seconds + "s ";

        // If the count down is finished, write some text
        

        if (distance < 0) {
            document.getElementById("CountDown").innerHTML = "Expiré";
           
            clearInterval(x);
            @if(Model.monObjet.Statut == enumStatutObjet.VD)
            {
               @:document.getElementById("CountDown").innerHTML = "Vendu";
            }
        }
    }, 1000);
</script>

Enchere/Enchere/Views/Home/Edit.cshtml
@model Enchere.Models.Encheree

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Encheree</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.UserId)
        @Html.HiddenFor(model => model.ObjetId)

        <div class="form-group">
            @Html.LabelFor(model => model.ObjetId, "ObjetId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Label("ObjetId",htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ObjetId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.LabelFor(model => model.user.UserName, "Nom Utilisateur", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.enchereNiveau, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.enchereNiveau, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.enchereNiveau, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.enchereDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.LabelFor(model => model.enchereDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.enchereDate, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Enchere/Enchere/Views/Home/GetMail.cshtml
@model Enchere.Models.mailSansAuth

@{
    ViewBag.Title = "GetMail";
}

@*<h2>Saisie Email</h2>*@


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Saisie email</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Envoyer" class="btn btn-default" />
                @*@Html.ActionLink("Liste des objets", "GetObjetsSansAuth", new { mail= Model.mail}, new { @class = "form-control" }) |*@
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>